# windows/action.yaml
name: Install Senzing SDK - windows
description: Install Senzing SDK on the windows platform.
author: support@senzing.com

inputs:
  senzingsdk-repository:
    description: Used for semantic version installs only, staging or production.
  senzingsdk-repository-path:
    description: Optional repository override for senzing packages outside of staging and production.
  senzingsdk-version:
    description: Version of Senzing SDK to install
    required: true

runs:
  using: composite
  steps:
    # Install latest staging or production image.

    - env:
        SENZING_INSTALL_VERSION: ${{ inputs.senzingsdk-version }}
        SENZINGSDK_REPOSITORY: ${{ inputs.senzingsdk-repository }}
        SENZINGSDK_REPOSITORY_PATH: ${{ inputs.senzingsdk-repository-path }}
      name: Install Senzing SDK
      shell: bash
      run: $GITHUB_ACTION_PATH/install-senzing.sh

branding:
  icon: download
  color: green
