name: Install Senzing SDK
description: Install Senzing SDK based on platform.
author: support@senzing.com

inputs:
  packages-to-install:
    description: Space separated list of Senzing packages to install. Linux only.
    default: "senzingsdk-runtime"
  senzingsdk-repository-package:
    description: Optional repository package override for senzing packages outside of staging and production. Linux only.
  senzingsdk-repository-path:
    description: Optional repository override for senzing packages outside of staging and production.
  senzingsdk-version:
    description: Version of Senzing SDK to install

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      name: Run on Linux
      uses: senzing-factory/github-action-install-senzing-sdk/linux@v3
      with:
        packages-to-install: ${{ inputs.packages-to-install }}
        senzingsdk-repository-package: ${{ inputs.senzingsdk-repository-package }}
        senzingsdk-repository-path: ${{ inputs.senzingsdk-repository-path }}
        senzingsdk-version: ${{ inputs.senzingsdk-version }}

    - if: runner.os == 'macOS'
      name: Run on macOS
      uses: senzing-factory/github-action-install-senzing-sdk/darwin@10-skern
      with:
        senzingsdk-repository-path: ${{ inputs.senzingsdk-repository-path }}
        senzingsdk-version: ${{ inputs.senzingsdk-version }}

    - if: runner.os == 'Windows'
      name: Run on Windows
      uses: senzing-factory/github-action-install-senzing-sdk/windows@v3
      with:
        senzingsdk-repository-path: ${{ inputs.senzingsdk-repository-path }}
        senzingsdk-version: ${{ inputs.senzingsdk-version }}

branding:
  icon: download
  color: green
